/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated', 
      dirName: '.',
      exclude: ['internal/**']  // Hide internal docs from sidebar
    }
  ],
};

export default sidebars;
